[package]
name = "hydra-sandbox"
version.workspace = true
edition.workspace = true
license.workspace = true
repository.workspace = true

[dependencies]
tokio = { workspace = true, features = ["full"] }
anyhow = { workspace = true }
uuid = { workspace = true }
rquickjs = { version = "0.12.2", features = ["full", "futures"] }
serde_json = { workspace = true }
serde = { workspace = true }

[dev-dependencies]
tempfile = { workspace = true }
